"""
Shared pytest fixtures for unit tests.
"""

import pytest
import warnings
from unittest.mock import AsyncMock, MagicMock, Mock, patch
from fastapi import WebSocket
from fastapi.testclient import TestClient
import sys
import os

# Note: PytestUnraisableExceptionWarning warnings from AWS CRT are expected and harmless.
# These occur when AWS CRT tries to complete futures that have been cancelled by mocks.
# They do not indicate test failures and can be safely ignored.
# Suppression attempts via filterwarnings or pytest hooks are not fully effective
# because these warnings are generated by pytest's unraisable exception handler,
# not standard Python warnings. The warnings are cosmetic and do not affect test results.

# Add src to path for imports
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'src'))

from agent import app


@pytest.fixture
def mock_websocket():
    """Mock WebSocket object for testing."""
    websocket = AsyncMock(spec=WebSocket)
    websocket.send_json = AsyncMock()
    websocket.receive_json = AsyncMock()
    websocket.accept = AsyncMock()
    return websocket


@pytest.fixture
def mock_nova_sonic_model():
    """Mock BidiNovaSonicModel for testing."""
    model = MagicMock()
    model.region = "us-east-1"
    model.model_id = "amazon.nova-sonic-v1:0"
    return model


@pytest.fixture
def mock_bidi_agent():
    """Mock BidiAgent for testing."""
    agent = MagicMock()
    agent.run = AsyncMock()
    agent.model = MagicMock()
    return agent


@pytest.fixture
def sample_audio_data():
    """Sample base64-encoded PCM audio data."""
    # Small PCM audio chunk (base64 encoded)
    return "AAAAAP//AAAAAAAAAAD//wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"


@pytest.fixture
def sample_text_data():
    """Sample text message data."""
    return "Hello, this is a test message"


@pytest.fixture
def app_client():
    """FastAPI test client."""
    return TestClient(app)


@pytest.fixture
def mock_requests_get(monkeypatch):
    """Mock requests.get for weather API tests."""
    mock_get = Mock()
    monkeypatch.setattr("requests.get", mock_get)
    return mock_get


@pytest.fixture
def mock_env_vars(monkeypatch):
    """Mock environment variables."""
    env_vars = {
        "AWS_REGION": "us-east-1",
        "MODEL_ID": "amazon.nova-sonic-v1:0",
        "VOICE": "matthew",
        "INPUT_SAMPLE_RATE": "16000",
        "OUTPUT_SAMPLE_RATE": "24000",
        "WEATHER_API_KEY": "test_api_key_12345",
    }
    for key, value in env_vars.items():
        monkeypatch.setenv(key, value)
    return env_vars


@pytest.fixture
def mock_bidi_events():
    """Helper to create mock BidiEvent objects."""
    class MockEvent:
        def __init__(self, event_type, **kwargs):
            self.event_type = event_type
            for key, value in kwargs.items():
                setattr(self, key, value)
    
    def create_event(event_type, **kwargs):
        event = MockEvent(event_type, **kwargs)
        # Set class name for isinstance checks
        event.__class__.__name__ = event_type
        return event
    
    return create_event

